WORDS = [
    'playground', 'basketball', 'helicopter', 'university', 'strawberry',
    'chimpanzee', 'watermelon', 'understand', 'television', 'restaurant',
    'lighthouse', 'skateboard', 'background', 'friendship', 'blackboard',
    'discipline', 'earthquake', 'everything', 'footprints', 'graduation',
    'importance', 'instructor', 'journalist', 'mysterious', 'newspapers',
    'obligation', 'operations', 'overweight', 'passionate', 'periodical',
    'physicians', 'presidents', 'protection', 'publishers', 'questioned',
    'recognized', 'remarkable', 'reputation', 'resolution', 'schoolwork',
    'simplicity', 'situations', 'skyscraper', 'solidarity', 'statistics',
    'structures', 'sunflowers', 'surprising', 'techniques', 'terrifying',
    'thoughtful', 'traditions', 'transplant', 'underneath', 'unfamiliar',
    'vegetables', 'wilderness', 'yesterdays', 'adjustment', 'attractive',
    'celebrated', 'commercial', 'compliance', 'considered', 'containers',
    'determined', 'developing', 'difference', 'dimensions', 'discussion',
    'economical', 'electrical', 'elementary', 'employment', 'encouraged',
    'engineered', 'enterprise', 'equivalent', 'everywhere', 'excitement',
    'exhibition', 'expedition', 'experience', 'explosions', 'foundation',
    'generosity', 'government', 'gymnastics', 'headphones', 'highlights',
    'historical', 'identified', 'increasing', 'incredible', 'innovation',
    'inspection', 'installing', 'integrated', 'interested', 'legislator',
]
